version: '3.8'
services:
  kachalka-backend:
    container_name: kachalka-backend
    image: openjdk:17-ea-16-jdk
    volumes:
      - ./kachalka-backend/build/libs/kachalka-backend-0.0.1-SNAPSHOT.jar:/kachalka-backend.jar
    command: [ "java", "-jar", "kachalka-backend.jar"]
    ports:
      - "8080:8080"
    networks:
      - kachalka-network
    depends_on:
      - kachalka-postgresql
      - kafka
      - keycloak

  sper-bank:
    container_name: sper-bank
    image: openjdk:17-ea-16-jdk
    volumes:
      - ./sper-bank/build/libs/sper-bank-0.0.1-SNAPSHOT.jar:/sper-bank.jar
    command: [ "java", "-jar", "sper-bank.jar"]
    networks:
      - kachalka-network
    depends_on:
      - kachalka-backend
      - sper-bank-postgresql

  kachalka-postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=kachalka
      - POSTGRES_DB=kachalka
      - POSTGRES_PASSWORD=kachalka
    volumes:
      - ./kachalka-backend/src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - kachalka-network

  sper-bank-postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=sper-bank
      - POSTGRES_DB=sper-bank
      - POSTGRES_PASSWORD=sper-bank
    volumes:
      - ./sper-bank/src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "667:5432"
    networks:
      - kachalka-network

  keycloak-postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=SUPERsecret
    volumes:
      - '/Users/k1b/Documents/study/postgresql_docker:/var/lib/postgresql/data'
    networks:
      - kachalka-network
    expose:
      - 5432
    hostname: "postgres"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    restart: always
    command: start-dev
    depends_on:
      - keycloak-postgresql
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_HOSTNAME_URL=http://keycloak:8080
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=SUPERsecret
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    networks:
      - kachalka-network
    ports:
      - "1337:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - kachalka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kachalka-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    networks:
      - kachalka-network

networks:
  kachalka-network:
    name: kachalka-network
    driver: bridge