spring:
  application:
    name: sper-bank
  r2dbc:
    url: r2dbc:postgresql://localhost:667/sper-bank
    username: sper-bank
    password: sper-bank
server:
  port: 8081

kachalka:
  baseUrl: http://localhost:8080